'use strict';

var Countrys = {
    AUSTRALIA: ['Canberra', 'Ballarat', 'Bendigo', 'Broadford', 'Geelong', 'La Trobe', 'Melbourne', 'Mildura', 'Swan Hill', 'Wodonga', 'Shepparton', 'Albany', 'Bunbury', 'Broome', 'Geraldton', 'Kalgoorlie', 'Carnarvon', 'Leonora', 'Mandurah', 'Meekatharra', 'Perth', 'Port Hedland', 'Tom Price', 'Wiluna', 'Esperance', 'Bundaberg', 'Brisbane',
        'Gympie'
        , 'Gladstone'
        , 'Gold Coast'
        , 'Ipswich'
        , 'Caloundra'
        , 'Cairns'
        , 'Mackay'
        , 'Mount Isa'
        , 'Maryborough'
        , 'Nambour'
        , 'Rockhampton'
        , 'Redcliffe'
        , 'Sunshine Coast'
        , 'Townsville'
        , 'Toowoomba'
        , 'Weipa'
        , 'Hervey Bay'
        , 'Charters Tower'
        , 'Armidale'
        , 'Bathurst'
        , 'Broken Hill'
        , 'Wyong'
        , 'Wollongong'
        , 'Gosford'
        , 'Goulburn'
        , 'Grafton'
        , 'Griffith'
        , 'Dubbo'
        , 'Katoomba'
        , 'Coffs Harbour'
        , 'Queanbeyan'
        , 'Lismore'
        , 'Lake Macquarie'
        , 'Maitland'
        , 'Nowra'
        , 'Newcastle'
        , 'Port'
        , 'Cessnock'
        , 'Sydney'
        , 'Tamworth'
        , 'Tweed Heads'
        , 'Wagga Wagga'
        , 'Alice Springs'
        , 'Darwin'
        , 'Palmerston'
        , 'Tennant Creek'
        , 'Burnie'
        , 'Devonport'
        , 'Launceston'
        , 'Hobart'
        , 'Adelaide'
        , 'Victor Harbor'
        , 'Murray Bridge'
        , 'Mount Gambier'
        , 'Port Lincoln'
        , 'Port Augusta'
        , 'Port Pirie'
        , 'Whyalla'],
    BRAZIL: [
        'Uberlandia'
        , 'Porto alegre'
        , 'São Goncalo'
        , 'Sao paulo'
        , 'Natal'
        , 'Brasilia'
        , 'Fortaleza'
        , 'Belen'
        , 'Curitiba'
        , 'Varzea Grande'
        , 'Taboan da Serra'
        , 'Gravatai'
        , 'Santa maria'
        , 'Taubate'
        , 'Governador Valadares'
        , 'Camacari'
        , 'Susana'
        , 'Mozoro'
        , 'Santarem'
        , 'Sao Jose dos Pinhais'
        , 'Recife'
        , 'Praia Grande'
        , 'Limeira'
        , 'Petropolis'
        , 'Guaruja'
        , 'Cascavel'
        , 'Boa vista'
        , 'Uberaba'
        , 'Ribeirão das Nevis'
        , 'Paulista'
        , 'Petroline'
        , 'Blumenau'
        , 'Ponta grossa'
        , 'Franca'
        , 'Canoas'
        , 'Vitoria da Conquista'
        , 'Pelotas'
        , 'Caruaru'
        , 'Itaquaquesetuba'
        , 'Caucaia'
        , 'Manaus'
        , 'Vitoria'
        , 'San Vicente'
        , 'Anapolis'
        , 'Rio branco'
        , 'Bauru'
        , 'Cariasica'
        , 'Piracicaba'
        , 'Olinda'
        , 'Karapikuiba'
        , 'Montis clarus'
        , 'Belo Horizonte'
        , 'Maring'
        , 'Jundiai'
        , 'Campina Grande'
        , 'Diadem'
        , 'Betin'
        , 'Mogi das Cruzes'
        , 'Santos'
        , 'Sao Jose do Rio Preto'
        , 'Macapa'
        , 'Maua'
        , 'São João di Meriti'
        , 'Florianopolis'
        , 'Vila Velha'
        , 'Caxias do Sul'
        , 'Serra'
        , 'Belford roshu'
        , 'Campus dos Goytacazis'
        , 'Porto Velho'
        , 'Niteroi'
        , 'Ananindeua'
        , 'Londrina'
        , 'Juis de Fora'
        , 'Joinville'
        , 'Cuiaba'
        , 'Feira di Santana'
        , 'Arakazhu'
        , 'Sorocaba'
        , 'Kontazhen'
        , 'Salvador'
        , 'Ribeirão Preto'
        , 'Zhabuatan dos Guararape'
        , 'Sao Jose dos Campos'
        , 'Ozasku'
        , 'Santo andré'
        , 'Joao Pesoa'
        , 'Nova Iguazu'
        , 'Sao bernardo do campo'
        , 'Teresina'
        , 'Campo Grande'
        , 'Rio de Janeiro'
        , 'Duki di caxias'
        , 'Maceio'
        , 'Sao luis'
        , 'Campinas'
        , 'Guarulhos'
        , 'Goiânia'
        , 'Viaman'
        , 'Empress'
        , 'Ipatinga'
        , 'Maraba'
        , 'Embu'
        , 'Barueri'
        , 'Volta Redonda'
        , 'Sumare'
        , 'Foz do Iguaçu'
        , 'Juazeiro do Norte'
        , 'Palmas'],
    GERMANY: [
        'Eisenach'
        , 'Eisenhüttenstadt'
        , 'Einbeck'
        , 'Aalen'
        , 'Albstadt'
        , 'Alsfeld'
        , 'Altenburg'
        , 'Amberg'
        , 'Anklam'
        , 'Ansbach'
        , 'Ahrensburg'
        , 'Augsburg'
        , 'Aurich'
        , 'Aue'
        , 'Aschaffenburg'
        , 'Bad Doberan'
        , 'Bad Kissingen'
        , 'Bad Arolsen'
        , 'Bad Bevensen'
        , 'Bad Wildungen'
        , 'Bad Wilsnack'
        , 'Bad Griesbach im Rottal'
        , 'Baden-Baden'
        , 'Bad Salzuflen'
        , 'Bad Langensalza'
        , 'Bad Mergentheim'
        , 'Bad Muskau'
        , 'Bad Neustadt an der Saale'
        , 'Bad Hersfeld'
        , 'Bad Zwischenahn'
        , 'Bad Staffelstein'
        , 'Bad Oeynhausen'
        , 'Bayreuth'
        , 'Balingen'
        , 'Bamberg'
        , 'Baunatal'
        , 'Bautzen'
        , 'Berlin'
        , 'Bernburg (Saale)'
        , 'Bernkastel-Kues'
        , 'Berchtesgaden'
        , 'Biberach an der Riss'
        , 'Bielefeld'
        , 'Bingen am Rhein'
        , 'Binz'
        , 'Bitburg'
        , 'Bodenmais'
        , 'Boltenhagen Ostseebad'
        , 'Bonn'
        , 'Bocholt'
        , 'Bochum'
        , 'Brandenburg an der Havel'
        , 'Braunau am Inn'
        , 'Braunschweig'
        , 'Bremen'
        , 'Bremerhaven'
        , 'Brilon'
        , 'Burg (bei Magdeburg)'
        , 'Burghausen'
        , 'Buchholz in der Nordheide'
        , 'Busüm'
        , 'Weiden in der Oberpfalz'
        , 'Weimar'
        , 'Wacken'
        , 'Walsrode'
        , 'Waren'
        , 'Wernigerode'
        , 'Werthaim'
        , 'Weeze'
        , 'Wetzlar'
        , 'Wyk auf Föhr'
        , 'Willingen'
        , 'Wilhelmshaven'
        , 'Winterberg'
        , 'Wiesbaden'
        , 'Wittenberge'
        , 'Wittstock'
        , 'Wolgast'
        , 'Wolfsburg'
        , 'Worms'
        , 'Wuppertal'
        , 'Wurzen'
        , 'Würzburg'
        , 'Heidelberg'
        , 'Halle (Saale)'
        , 'Hamburg'
        , 'Hann. Münden'
        , 'Hannover'
        , 'Gardelegen'
        , 'Garmish-Partenkirchen'
        , 'Genthin'
        , 'Gera'
        , 'Görlitz'
        , 'Göttingen'
        , 'Giessen'
        , 'Goslar'
        , 'Gotha'
        , 'Greifswald'
        , 'Grafenwöhr'
        , 'Grimma'
        , 'Guben'
        , 'Gummersbach'
        , 'Günzburg'
        , 'Güstrow'
        , 'Damp'
        , 'Darmstadt'
        , 'Dachau'
        , 'Delmenhorst'
        , 'Demmin'
        , 'Dessau-Rosslau'
        , 'Detmold'
        , 'Dingolfing'
        , 'Dortmund'
        , 'Dresden'
        , 'Duisburg'
        , 'Düren'
        , 'Düsseldorf'
        , 'Salzwedel'
        , 'Salzgitter'
        , 'Sassnitz'
        , 'Sellin'
        , 'Siegen'
        , 'Singen'
        , 'Soltau'
        , 'Sonderhausen'
        , 'Suhl'
        , 'Idar-Oberstein'
        , 'Iserlohn'
        , 'Ilmenau'
        , 'Uelzen'
        , 'Ingolstadt'
        , 'Itzehoe'
        , 'Jena'
        , 'Kaiserslautern'
        , 'Cham'
        , 'Karlsruhe'
        , 'Kassel'
        , 'Quedlingburg'
        , 'Köln'
        , 'Kelheim'
        , 'Kempten'
        , 'Köthen'
        , 'Kiel'
        , 'kitzingen'
        , 'Clausthal-Zellerfeld'
        , 'Cloppenburg'
        , 'Koblenz'
        , 'Coburg'
        , 'Konstanz'
        , 'Cottbus'
        , 'Cochem'
        , 'Crailsheim'
        , 'Cuxhaven'
        , 'Kulmbach'
        , 'Kuhlungsborn'
        , 'Landsberg am Lech'
        , 'Landshut'
        , 'Leverkusen'
        , 'Leipzig'
        , 'Leer'
        , 'Limburg an der Lahn'
        , 'Lingen'
        , 'Lippstadt'
        , 'Leuna'
        , 'Lubbenau (Spreewald)'
        , 'Lübeck'
        , 'Ludwigsburg'
        , 'Lüneburg'
        , 'Lutherstadt Eisleben'
        , 'Magdeburg'
        , 'Mayen'
        , 'Meiningen'
        , 'Mainz'
        , 'Maissen'
        , 'Vfyutqv'
        , 'Marburg'
        , 'Marktredwitz'
        , 'Memmingen'
        , 'Mönchengladbach'
        , 'Meppen'
        , 'Minden'
        , 'Mittenwald'
        , 'Münster'
        , 'München'
        , 'Naumburg (Saale)'
        , 'Nördlingen'
        , 'Niebüll'
        , 'Nienburg'
        , 'Neubrandenburg'
        , 'neumarkt in der Oberpfalz'
        , 'Neumünster'
        , 'Neuruppin'
        , 'Neustadt in Holstein'
        , 'Neustrelitz'
        , 'Norden'
        , 'Nordenham'
        , 'Norderney'
        , 'Norderstedt'
        , 'Nordhausen'
        , 'Nordhorn'
        , 'Northeim'
        , 'Nürburg'
        , 'Nürnberg'
        , 'Obersdorf'
        , 'Oberhof'
        , 'Oldenburg'
        , 'Oranienburg'
        , 'Osnabrück'
        , 'Offenbach am Main'
        , 'Offenburg'
        , 'Padenborn'
        , 'Pasewalk'
        , 'Peine'
        , 'Papenburg'
        , 'Parchim'
        , 'Passau'
        , 'Poel Insel'
        , 'Pirmasens'
        , 'Perna'
        , 'Plau am See'
        , 'Plauen'
        , 'Potsdam'
        , 'Prenzlau'
        , 'Prien am Chiemsee'
        , 'Pforzheim'
        , 'Ravensburg'
        , 'Rheine'
        , 'Rheinsberg'
        , 'Rathenow'
        , 'Regen'
        , 'Regensburg'
        , 'Rendsburg'
        , 'Ribnitz-Damgarten'
        , 'Riesa'
        , 'Rosenheim'
        , 'Reutlingen'
        , 'Rostock'
        , 'Rothenburg ob der Tauber'
        , 'Rust'
        , 'Rügen'
        , 'Saarlouis'
        , 'St. Peter-Ording'
        , 'Saabrucken'
        , 'Tegernsee'
        , 'Templin'
        , 'Timmendorfer-Strand'
        , 'Titisee Neustadt'
        , 'Torgau'
        , 'Trier'
        , 'Tübingen'
        , 'Ulm'
        , 'Feldberger-Seenlandschaft'
        , 'Fehmarn'
        , 'Verden (Aller)'
        , 'Vechta'
        , 'Villingen-Schwenningen'
        , 'Flensburg'
        , 'Forst (Lausitz)'
        , 'Freiberg'
        , 'Freiburg im Breisgau'
        , 'Freising'
        , 'Frankfurt (Oder)'
        , 'Frankfurt am Main'
        , 'Friedrichshafen'
        , 'Fulda'
        , 'Furth im Wald'
        , 'Heide'
        , 'Heidenau'
        , 'Heidenheim an der Brenz'
        , 'Heiligenhafen'
        , 'Heilbronn'
        , 'Halbe'
        , 'Halberstadt'
        , 'Hameln'
        , 'Hamm'
        , 'Hanau'
        , 'Haren'
        , 'Havelberg Hansestadt'
        , 'Helgoland'
        , 'Helmstedt'
        , 'Chemnitz'
        , 'Heringsdorf'
        , 'Herzogenaurach'
        , 'Hiddensee'
        , 'Hildeshaim'
        , 'Hoyerswerda'
        , 'Hof'
        , 'Husum'
        , 'Zweibrücken'
        , 'Zwickau'
        , 'Celle'
        , 'Zinnowitz'
        , 'Schweinfurt'
        , 'Schwangau'
        , 'Schwandorf'
        , 'Schwedt (Oder)'
        , 'Schwerin'
        , 'Schkeuditz'
        , 'Schleswig'
        , 'Stade'
        , 'Starnberg'
        , 'Stendal'
        , 'Stralsund'
        , 'Straubing'
        , 'Stuhr'
        , 'Stuttgart'
        , 'Elmshorn'
        , 'Emden'
        , 'Emsdetten'
        , 'Erding'
        , 'Erlangen'
        , 'Erfurt'
        , 'Essen'
        , 'Eschwege'
    ],
    SPAIN: [
        'Madrid'
        , 'Barcelona'
        , 'Valencia'
        , 'Sevilla'
        , 'Zaragoza'
        , 'Malaga'
        , 'Murcia'
        , 'Palma'
        , 'Las Palmas de Gran Canaria'
        , 'Bilbao'
        , 'Alicante'
        , 'Cordoba'
        , 'Valladolid'
        , 'Gijon'
        , 'L’Hospitalet de Llobregat'
        , 'La Coruna'
        , 'Granada'
        , 'Vitoria'
        , 'Elche'
        , 'Oviedo'
        , 'Santa Cruz de Tenerife'
        , 'Badalona'
        , 'Cartagena'
        , 'Jerez de la Frontera'
        , 'Alcala de Henares'],
    FRANCE: [
        'Paris'
        , 'Marseille'
        , 'Lyon'
        , 'Toulouse'
        , 'Nice    Alpe'
        , 'Nantes    The'
        , 'Strasbourg'
        , 'Montpellier'
        , 'Bordeaux'
        , 'Lille'
        , 'Ren'
        , 'Reims'
        , 'Grenoble'
        , 'Dijon'
        , 'It    Gard'
        , 'Angers    Of Maine - et - Loire'
        , 'Villeurbanne'
        , 'Le Mans    Sarta'
        , 'Saint - DenisAIX - EN - Provence'
        , 'Clermont - Ferrand'
        , 'Brest'
        , 'Limoges'
        , 'Tour'
        , 'Amiens'
        , 'Perpignan'
        , 'Mets'
        , 'Besançon'
        , 'Boulogne - Billanc'
        , 'Orleans    Loire'
        , 'Mulhouse'
        , 'Rouen'
        , 'Saint - Denis'
        , 'Kan    Calvados'
        , 'Argenteuil'
        , 'Saint - Paul32'
        , 'Montreuil'
        , 'Nancy'
        , 'oumea4'
        , 'Nanterre'
        , 'Avignon    Vaucluse'
        , 'Vitry - sur - Seine'
        , 'Créteil'
        , 'Dunkirk'
        , 'Poitiers'
        , 'Asnieres - sur - Seine'
        , 'Courbevoie'
        , 'Versailles'
        , 'Colombes'
        , 'Fort - de - France'
        , 'Aunay - sous - Bois'
        , 'Saint - Pierre'
        , 'At    The Atlantic'
        , 'Le Tampon'
        , 'Antibes'
        , 'Beziers    Eero'
        , 'La Rochelle'
        , 'Saint - Maur - des - fossés'
        , 'Cannes'
        , 'Calais'
        , 'Saint - Nazaire'
        , 'Merignac'
        , 'Drancy'
        , 'Colmar'
        , 'Ajaccio'
        , 'Bourges    Cher'
        , 'Issy - Les - Moulineaux'
        , 'Levallois - Perret'
        , 'La - Seine - sur - Mer'
        , 'Kemper    Finistère'
        , 'Noisy - Le - Grand'
        , 'Villeneuve'
        , 'Neuilly - sur - Seine'
        , 'Valence    Drom'
        , 'Anthony'
        , 'CERGY'
        , 'Vénissieux'
        , 'Pessac'
        , 'Troyes'
        , 'Clichy - La - Garenne'
        , 'Ivry - sur - Seine'
        , 'Chambery'
        , 'Lorient    Morbihan'
        , 'Les Abim'
        , 'Montauban'
        , 'Sarcelles'
        , 'Niort'
        , 'Mamutu'
        , 'Villejuif'
        , 'Saint - andré'
        , 'Yer    Var'
        , 'Saint - Quentin'
        , 'Beauvais'
    ],
    ITALY: [
        'Rome'
        , 'Milan'
        , 'Naples'
        , 'Turin'
        , 'Palermo'
        , 'Genoa'
        , 'Bologna'
        , 'Florence'
        , 'Bari'
        , 'Catania'
        , 'Venice'
        , 'Verona'
        , 'Messina'
        , 'Padova'
        , 'Trieste'
        , 'Taranto'
        , 'Brescia'
        , 'Prato'
        , 'Parma'
        , 'Modena'
        , 'Reggio di Calabria'
        , 'Reggio Nell emilia'
        , 'Perugia'
        , 'Livorno'
        , 'Ravenna'
        , 'Cagliari'
        , 'Foggia'
        , 'Rimini'
        , 'Ferrara'
        , 'Salerno'
        , 'Sassari'
        , 'Latina'
        , 'Monza'
        , 'Siracusa'
        , 'Pescara'
        , 'Giugliano in Campania'
        , 'Bergamo'
        , 'Forli'
        , 'Trento'
        , 'Vicenza'
        , 'Terni'
        , 'Bolzano'
        , 'Novara'
        , 'Piacenza'
        , 'Ancona'
        , 'Andria'


    ],
    MEXICO: [

        'Abasolo'
        , 'Abasolo'
        , 'Agua Dulce'
        , 'Agualeguas'
        , 'Agua Prieta'
        , 'Aguascalientes'
        , 'Akaltan-de-Perez-Figueroa'
        , 'Acambaro'
        , 'Acanceh'
        , 'Acaponeta'
        , 'Acapulco'
        , 'Acatlan-de-Juarez'
        , 'Acayucan'
        , 'Aconchi'
        , 'Actopan'
        , 'Actopan'
        , 'Alamos'
        , 'Alvarado'
        , 'Allende'
        , 'Allende'
        , 'Altar'
        , 'Altotonga'
        , 'Amacuzac'
        , 'Amatitan'
        , 'Amatlán'
        , 'Amealco'
        , 'Ameca'
        , 'Amecameca'
        , 'Angostura'
        , 'Antiguo Morelos'
        , 'Antunes'
        , 'Ahome'
        , 'APAM'
        , 'Apizaco'
        , 'Apodaca'
        , 'Arandas'
        , 'Ario de Rosales'
        , 'Arizpe'
        , 'Thrift'
        , 'Arriaga'
        , 'Arcelia'
        , 'Arteaga'
        , 'Atengo'
        , 'Atencingo'
        , 'Atlas'
        , 'Atlixco'
        , 'Atotonilco El Alto'
        , 'Atoyac de Alvarez'
        , 'Ahuacatlan'
        , 'Ahualulco'
        , 'Autlan'
        , 'Ayutla'
        , 'Baviacora'
        , 'Badiraguato'
        , 'Bahía Kino'
        , 'Tank'
        , 'Bacalar'
        , 'Bacum'
        , 'Balance'
        , 'Bekal'
        , 'Benito Juarez'
        , 'Benjamín Hill'
        , 'Bermejillo'
        , 'Boca del Rio'
        , 'Bustamante'
        , 'Buenaventura'
        , 'BUENAVISTA'
        , 'Valle de Banderas'
        , 'Valle de Bravo'
        , 'Valle de Santiago'
        , 'Valle de Zaragoza'
        , 'Valparaiso'
        , 'Valladolid'
        , 'Venado'
        , 'Venustiano Carranza'
        , 'Venustiano Carranza'
        , 'Venustiano Carranza'
        , 'Venustiano Carranza'
        , 'Veracruz'
        , 'Villa Hidalgo'
        , 'Villa Ahumada'
        , 'Villagran'
        , 'Villagran'
        , 'Villa de Arriaga'
        , 'Villa de cos'
        , 'Villa Hidalgo'
        , 'Villa Hidalgo'
        , 'Villa Hidalgo'
        , 'Villa Corona'
        , 'Villa Lopez'
        , 'Villa Unión'
        , 'Villa Unión'
        , 'Villa Unión'
        , 'Villa-Flores'
        , 'Villa Juarez'
        , 'Villa Juarez'
        , 'Villa Juarez'
        , 'Vicente Guerrero'
        , 'Vicente Guerrero'
        , 'Viesca'
        , 'Galeana'
        , 'Guadalajara'
        , 'Gomez Farias'
        , 'Gonzalez'
        , 'Guadalupe'
        , 'Guadalupe Victoria'
        , 'Guadalupe y Calvo'
        , 'Guaymas'
        , 'Guamuchil'
        , 'Guanacevi'
        , 'Guanajuato'
        , 'Guasave'
        , 'Dimas'
        , 'Doctor Arroyo'
        , 'Dr. Gonzalez'
        , 'Doctor Mora'
        , 'Dolores Hidalgo'
        , 'Dong'
        , 'Durango'
        , 'Iguala'
        , 'Hidalgo'
        , 'Irapuato'
        , 'Izamal'
        , 'Isla'
        , 'Ixtapa'
        , 'Ixtepec'
        , 'Ixtlan del Rio'
        , 'Ixtlan de Juarez'
        , 'Cadereyta'
        , 'Cadereyta'
        , 'Calera Victor Rosales'
        , 'Caliban'
        , 'Calvillo'
        , 'Calkini'
        , 'Calnali'
        , 'The Calpulalpan'
        , 'Campeche'
        , 'Cananea'
        , 'Canatlan'
        , 'Candela'
        , 'Candelaria'
        , 'Cancun'
        , 'Carbo'
        , 'Cardenas'
        , 'Cardenas'
        , 'Castaignos'
        , 'Catemaco'
        , 'Queretaro'
        , 'Queretaro'
        , 'Qila'
        , 'Qila'
        , 'Quiroga'
        , 'Coalcoman'
        , 'Coyotepec'
        , 'Cocula'
        , 'Cocula'
        , 'Colombia'
        , 'Colon'
        , 'Colorines'
        , 'Colotlan'
        , 'Comalcalco'
        , 'Comitan'
        , 'Compostela'
        , 'Conkal'
        , 'Concordia'
        , 'Concordia'
        , 'Concepcion del Oro'
        , 'Copainala'
        , 'Digging'
        , 'Cordoba'
        , 'Cortazar'
        , 'Cosala'
        , 'Cosamaloapan'
        , 'Coscomatepec'
        , 'Costa Rica'
        , 'Cozumel'
        , 'Coyuca de Benitez'
        , 'Coyutla'
        , 'Cruz Grande'
        , 'Cuatro Cienegas'
        , 'Cuauhtemoc'
        , 'Cuautla'
        , 'Cuautla'
        , 'Cuicatlan'
        , 'Culiacan'
        , 'Cumpas'
        , 'Cunduacan'
        , 'Cuencame de Ceniceros'
        , 'Cuernavaca'
        , 'The cuetzalán'
        , 'La Antigua'
        , 'La Barca'
        , 'La Venta'
        , 'Lagos de Moreno'
        , 'La Cruz'
        , 'La Mission'
        , 'Lampasas'
        , 'La Paz'
        , 'La Piedad'
        , 'Lazaro Cardenas'
        , 'Las Varas'
        , 'Las Margaritas'
        , 'Las Nieves'
        , 'Las Esperanzas'
        , 'La Huacana'
        , 'La Huerta'
        , 'Leon'
        , 'Lerdo'
        , 'Lerma'
        , 'Linares'
        , 'Loma Bonita'
        , 'Loreto'
        , 'Loreto'
        , 'Los Aldamas'
        , 'Los Mochis'
        , 'Los Ramones'
        , 'Los Reyes'
        , 'Los Herreras'
        , 'Magdalena'
        , 'Magdalena'
        , 'Madrid'
        , 'Manzanillo'
        , 'Manuel'
        , 'Mapastepec'
        , 'Mapimi'
        , 'Maravatio'
        , 'Marcelia'
        , 'Mazatan'
        , 'Mazatlan'
        , 'Mazatlan'
        , 'Mascot'
        , 'Matamoros'
        , 'Matamoros (Tamaulipas state)'
        , 'Matehuala'
        , 'Matias Romero'
        , 'Melchor Ocampo'
        , 'Merida'
        , 'Mezcala'
        , 'Mezquitic'
        , 'Mexico city'
        , 'Miguel AUSA'
        , 'Mine'
        , 'Misantla'
        , 'Mitla'
        , 'Mocorito'
        , 'Molango'
        , 'Monclova'
        , 'Montemorelos'
        , 'Monterrey'
        , 'Monte Escobedo'
        , 'Morelia'
        , 'Moroleon'
        , 'Motozintla'
        , 'Motul'
        , 'Moon'
        , 'Nava'
        , 'Navolato'
        , 'Navojoa'
        , 'Nike'
        , 'NACO'
        , 'Nacozari'
        , 'NASAs'
        , 'Nogales'
        , 'Numaran'
        , 'Nueva Italy'
        , 'Nueva Casas Grandes'
        , 'Nueva Rosita'
        , 'Nuevo Laredo'
        , 'Nuevo Leon'
        , 'About'
        , 'Oaxaca'
        , 'Ocampo'
        , 'Ocosingo'
        , 'Ocozocoautla'
        , 'Ocotlan'
        , 'Olinala'
        , 'Isla Holbox'
        , 'Ometepec'
        , 'Orizaba'
        , 'The Oriental'
        , 'Ozuluama'
        , 'Ojinaga'
        , 'Ojocaliente'
        , 'Ojuelos'
        , 'Palenque'
        , 'Palisade'
        , 'Palmyra'
        , 'Panabá'
        , 'Panandikar'
        , 'Panuco'
        , 'Papantla'
        , 'Paraíso'
        , 'Paredon'
        , 'Paso de Ovejas'
        , 'Pachuca'
        , 'Penjamo'
        , 'Pericos'
        , 'Perote'
        , 'The Pescheria'
        , 'Petatlan'
        , 'Pet'
        , 'Pinos'
        , 'The Pinotepa Nacional'
        , 'Pijijiapan'
        , 'Pichucalco'
        , 'Playa Vicente'
        , 'Poza Rica'
        , 'Potam'
        , 'Puruandiro'
        , 'Puebla'
        , 'Pueblo Nuevo'
        , 'Puerto Vallarta'
        , 'Puerto Morelos'
        , 'Puerto Peñasco'
        , 'Puerto ESCONDIDO'
        , 'Piedras Negras'
        , 'Piedras Negras'
        , 'District'
        , 'Reynosa'
        , 'Reform'
        , 'Rincon de Romos'
        , 'Rio Bravo'
        , 'Rio Verde'
        , 'Rio Grande'
        , 'Rodeo'
        , 'Rosamorada'
        , 'Rosario'
        , 'Rosarito'
        , 'Zaachila'
        , 'Sabancuy'
        , 'Sabinas'
        , 'Sabinas Hidalgo'
        , 'Zacapoaxtla'
        , 'Zacapu'
        , 'Zacatecas'
        , 'Zacatlan'
        , 'Zacoalco'
        , 'Salamanca'
        , 'Salina Cruz'
        , 'Salinas de Hidalgo'
        , 'Salvatierra'
        , 'Saltillo'
        , 'Saltillo'
        , 'Zamora'
        , 'San Andres Tuxtla'
        , 'San Blas'
        , 'San Blas'
        , 'San Buenaventura'
        , 'San Gabriel Chilac'
        , 'San Ignacio'
        , 'San Ignacio'
        , 'San Quintin'
        , 'San Cristobal de Las Casas'
        , 'San Luis Acatlan'
        , 'San Luis de La Loma'
        , 'San Luis de La Paz'
        , 'San Luis del Cordero'
        , 'San Luis Potosi'
        , 'San Luis Rio Colorado'
        , 'San Lucas'
        , 'San Marcos'
        , 'San Marcos'
        , 'San Martin Hidalgo'
        , 'San Miguel El Alto'
        , 'San Pablo-Bales'
        , 'San-Pedro-de-La-Colonies'
        , 'San Ramon'
        , 'San Rafael'
        , 'San Salvador El SECO'
        , 'Santa Ana'
        , 'Santa Barbara'
        , 'Santa Maria del Oro'
        , 'Santa Maria del Oro'
        , 'Santa Maria del Rio'
        , 'Santa Rosalia'
        , 'Santiago'
        , 'Santiago Ixcuintla'
        , 'Santiago Papasquiaro'
        , 'Santiago Tuxtla'
        , 'San Felipe'
        , 'San Felipe'
        , 'San Fernando'
        , 'San Fernando'
        , 'San Francisco del Oro'
        , 'San Francisco del rincón'
        , 'San Jeronimito'
        , 'San Jose de Gracia'
        , 'San Jose de Gracia'
        , 'San Jose del Cabo'
        , 'San Juan de Guadalupe'
        , 'San Juan de Los Lagos'
        , 'San Juan del Rio'
        , 'San Juan del Rio'
        , 'San Juan Evangelista'
        , 'Of zapotitlán'
        , 'Zaragoza'
        , 'Zaragoza'
        , 'Sauyo'
        , 'Susilo'
        , 'Sayula'
        , 'Cedral'
        , 'Celaya'
        , 'Celestun'
        , 'Santispac'
        , 'Cerralvo'
        , 'Cerritos'
        , 'Cerro Azul'
        , 'Selachian'
        , 'Silao'
        , 'Zimapan'
        , 'Zimatlán de Alvarez'
        , 'Simojovel'
        , 'Sinaloa'
        , 'Sinaloa de Leyva'
        , 'Zinapecuaro'
        , 'Cintalapa'
        , 'Soledad de Doblado'
        , 'Sombrerete'
        , 'Zongolica'
        , 'Sonoyta'
        , 'Soto La Marina'
        , 'Sotuta'
        , 'Sumpango'
        , 'Zumpango del Rio'
        , 'Suchiapa'
        , 'Ciudad Obregon'
        , 'Ciudad Victoria'
        , 'Ciudad Guerrero'
        , 'Ciudad Guzmán'
        , 'Ciudad Delicias'
        , 'Ciudad del Carmen'
        , 'Ciudad del Maiz'
        , 'Ciudad Hidalgo'
        , 'Ciudad Hidalgo'
        , 'Ciudad Camargo'
        , 'Ciudad Camargo'
        , 'Ciudad Mante'
        , 'Ciudad Pemex'
        , 'Ciudad Sahagun'
        , 'Ciudad Serdan'
        , 'Ciudad Juarez'
        , 'Tabasco'
        , 'Tacambaro'
        , 'Tacotalpa'
        , 'Talpa de Allende'
        , 'Tamazula'
        , 'Tamazula'
        , 'Tamazulapan'
        , 'Tamazunchale'
        , 'Tampico'
        , 'Tamuin'
        , 'Tamiahua'
        , 'Tancitaro'
        , 'Tantoyuca'
        , 'Tapalpa'
        , 'Tapachula'
        , 'Taxco'
        , 'Teapa'
        , 'Tecalitlan'
        , 'Tecamachalco'
        , 'Tecate'
        , 'Tecolotlan'
        , 'Tecolutla'
        , 'Tecoman'
        , 'Tecuala'
        , 'Teloloapan'
        , 'Temosachic'
        , 'Tempoal'
        , 'Tenabo'
        , 'Tenancingo'
        , 'Tenosique'
        , 'Teocaltiche'
        , 'Teocelo'
        , 'Teotitlan del Camino'
        , 'Tepalcingo'
        , 'Tepatitlán'
        , 'Tepeaca'
        , 'Tepehuanes'
        , 'Tepeji del Rio'
        , 'Tepic'
        , 'Texcoco'
        , 'Teziutlan'
        , 'Tehuacan'
        , 'Tehuantepec'
        , 'Tehuitzingo'
        , 'Tiquicheo'
        , 'Ticul'
        , 'Tingambato'
        , 'Tisimin'
        , 'Title'
        , 'Tihuatlan'
        , 'Tijuana'
        , 'Tlaquepaque'
        , 'Tlacoachistlahuaca'
        , 'Tlacotepec'
        , 'Tlacotepec'
        , 'Tlacojalpan'
        , 'Tlapa de Comonfort'
        , 'Tlaxcala'
        , 'Tlaxco'
        , 'Tlahualilo de Zaragoza'
        , 'Todos Santos'
        , 'Toluca'
        , 'Tomatlan'
        , 'Tonala'
        , 'Tonaya'
        , 'Tonila'
        , 'Topolobampo'
        , 'Torreon'
        , 'Tula'
        , 'Tula'
        , 'Tulancingo'
        , 'Tuxpan'
        , 'Tuxpan'
        , 'Tuxpan'
        , 'Tuxpan'
        , 'Tuxtepec'
        , 'Tuxtla Gutierrez'
        , 'Tuxtla Chico'
        , 'Tierra Blanca'
        , 'Tierra Colorada'
        , 'Tierra Nueva'
        , 'Hualahuises'
        , 'Huamantla'
        , 'Huamuxtitlan'
        , 'Wasabis'
        , 'Huatabampo'
        , 'Huatusco de chicuellar'
        , 'The huauchinango'
        , 'Huajuapan de Leon'
        , 'Machinery'
        , 'Huimanguillo'
        , 'Mitsuko'
        , 'Huichapan'
        , 'Uman'
        , 'Unión de Tula'
        , 'Unión Hidalgo'
        , 'Ures'
        , 'Uruapan'
        , 'Huetamo'
        , 'Huehuetan'
        , 'Huejuquilla El Alto'
        , 'Felipe-Carrillo-Puerto'
        , 'Frontera'
        , 'Fronteras'
        , 'Jalapa'
        , 'Jalapa'
        , 'Halacha'
        , 'Jalpa'
        , 'Jalpa de Mendez'
        , 'Jaltepec'
        , 'Jaltipan'
        , 'Jamapa'
        , 'The milkfish'
        , 'Jaral del Progreso'
        , 'Jaumave'
        , 'Jerez de Garcia Salinas'
        , 'Jesus Carranza'
        , 'Jesús María'
        , 'Jesús María'
        , 'Jilotepec'
        , 'Jocotepec'
        , 'Jonacatepec'
        , 'Jonuta'
        , 'Hopelchen'
        , 'Jojutla'
        , 'Juan Aldama'
        , 'Juanita'
        , 'Juarez'
        , 'Holmes'
        , 'Honoka'
        , 'Juchipila'
        , 'Juchitán'
        , 'Juchitlan'
        , 'Chalchihuites'
        , 'Champoton'
        , 'Chapala'
        , 'CHARCAS'
        , 'Chetumal'
        , 'Chignahuapan'
        , 'Chicomuselo'
        , 'Chicontepec'
        , 'Chilapa'
        , 'Chinameka'
        , 'Chihuahua'
        , 'Choys'
        , 'Cholula'
        , 'Abano'
        , 'Eldorado'
        , 'El Coyote'
        , 'El Mesquite'
        , 'El Oro'
        , 'El Porvenir'
        , 'El Salado'
        , 'El Salto'
        , 'El Triunfo'
        , 'El Fuerte'
        , 'Emiliano Zapata'
        , 'Emiliano Zapata'
        , 'Emiliano Zapata'
        , 'Empalme'
        , 'Encarnación de díaz'
        , 'Ensenada'
        , 'Hermosillo'
        , 'Escuinapa'
        , 'Escuintla'
        , 'Espite'
        , 'Etchojoa'
        , 'Ejutla'
        , 'Ejutla'
        , 'Yurecuaro'
        , 'Yuriria'
        , 'Yavaros'
        , 'Yahualica'
        , 'Yautepec de Zaragoza'

    ],
    UK: [

        'City of London'
        , 'London'
        , 'Birmingham'
        , 'Glasgow'
        , 'Liverpool'
        , 'Leeds'
        , 'Sheffield'
        , 'Edinburgh'
        , 'Bristol'
        , 'Manchester'
        , 'Leicester'
        , 'Islington'
        , 'Coventry'
        , 'Hull'
        , 'Cardiff'
        , 'Bradford'
        , 'Belfast'
        , 'Stoke-on-Trent'
        , 'Wolverhampton'
        , 'Plymouth'
        , 'Nottingham'
        , 'Southampton'
        , 'Reading'
        , 'Derby'
        , 'Bexley'
        , 'Dudley'
        , 'Northampton'
        , 'Portsmouth'
        , 'Luton'
        , 'Newcastle upon Tyne'
        , 'Preston'
        , 'Sutton'
        , 'Milton Keynes'
        , 'Aberdeen'
        , 'Sunderland'
        , 'Norwich'
        , 'Walsall'
        , 'Swansea'
        , 'Bournemouth'
        , 'Southend-on-Sea'
        , 'Swindon'
        , 'Oxford'
        , 'Dundee'
        , 'Poole'
        , 'Huddersfield'
        , 'York'
        , 'Ipswich'
        , 'Blackpool'
        , 'Middlesbrough'
        , 'Bolton'
        , 'Aireborough'
        , 'Avon'
        , 'Bedfordshire'
        , 'Belfast'
        , 'Berkshire'
        , 'Britannia'
        , 'Britannia Inferior'
        , 'Britannia Superior'
        , 'Central Region'
        , 'Clwyd'
        , 'County of Cheshire'
        , 'Dyfed'
        , 'England'
        , 'Grampian Region'
        , 'Greater Manchester'
        , 'Hereford and Worcester'
        , 'Humberside'
        , 'Lothian Region'
        , 'Merseyside'
        , 'Mid Glamorgan'
        , 'Northern Ireland'
        , 'Scotland'
        , 'South Glamorgan'
        , 'South Yorkshire'
        , 'Spenborough'
        , 'Strathclyde Region'
        , 'Tayside Region'
        , 'Tyne and Wear'
        , 'Wales'
        , 'West Glamorgan'
        , 'West Midlands'
        , 'West Suffolk'
        , 'West Yorkshire'


    ]
};